DELIMITER //

DROP PROCEDURE IF EXISTS GETEDUCESCUELA;

CREATE PROCEDURE GETEDUCESCUELA(EID INT)
BEGIN
    SELECT
        TNES.ID, 
        TED.ID AS IDTIPOEDUCACION,
        TED.NOMBRE AS TIPO,
        NED.ID AS IDNIVELEDUCACION,
        NED.NOMBRE AS NIVEL         
    FROM TedNivEscuela TNES
    INNER JOIN TipoNivelEducacion TNED
        ON TNED.ID = TNES.IDTIPONIVEL
    INNER JOIN TipoEducacion TED 
        ON TED.ID = TNED.IDTIPOEDUCACION
    INNER JOIN NvelEducacion NED 
        ON NED.ID = TNED.IDNIVELEDUCACION
    WHERE TNES.IDESCUELA = EID;

END //

DELIMITER ;