DELIMITER //

DROP PROCEDURE IF EXISTS GETTIPONIVELEDUCACION;

CREATE PROCEDURE GETTIPONIVELEDUCACION(TEDID INT)
BEGIN
    IF TEDID = -1 THEN
        SELECT 
            TNE.ID AS ID, 
            TED.ID AS IDTIPOEDUCACION, 
            TED.NOMBRE AS NOMBRETIPOEDUCACION, 
            NE.ID AS IDNIVELEDUCACION, 
            NE.NOMBRE AS NOMBRENIVELEDUCACION
        FROM TipoNivelEducacion AS TNE
        INNER JOIN  TipoEducacion AS TED
            ON TED.ID = TNE.IDTIPOEDUCACION
        INNER JOIN NivelEducacion NE
            ON NE.ID = TNE.IDNIVELEDUCACION
        ORDER BY TNE.ID;
    ELSE
        SELECT 
            TNE.ID AS ID, 
            TED.ID AS IDTIPOEDUCACION, 
            TED.NOMBRE AS NOMBRETIPOEDUCACION, 
            NE.ID AS IDNIVELEDUCACION, 
            NE.NOMBRE AS NOMBRENIVELEDUCACION
        FROM TipoNivelEducacion AS TNE
        INNER JOIN  TipoEducacion AS TED
            ON TED.ID = TNE.IDTIPOEDUCACION
        INNER JOIN NivelEducacion NE
            ON NE.ID = TNE.IDNIVELEDUCACION
        WHERE TED.ID = TEDID
        ORDER BY TNE.ID;
    END IF;
END //

DELIMITER ;
