DELIMITER //

DROP PROCEDURE IF EXISTS POSTTIPOEDUCACION;

CREATE PROCEDURE POSTTIPOEDUCACION(
    pnombre VARCHAR(256)
    ,OUT out_id INT)
BEGIN
    INSERT INTO TipoEducacion (
        nombre
    ) VALUES (
        pnombre
    );

    SET out_id = LAST_INSERT_ID();
END; //

DELIMITER ;
