drop view if exists Encierro;
create view Encierro as
          select  1 as idTN, CUE_Anexo as Codigo from DatosBase where Ed_Contexto_de_Encierro = 'X' and Ed_Comun_Jardin_maternal = 'X'             
union all select  2 as idTN, CUE_Anexo as Codigo from DatosBase where Ed_Contexto_de_Encierro = 'X' and Ed_Comun_Inicial    = 'X'                     
union all select  3 as idTN, CUE_Anexo as Codigo from DatosBase where Ed_Contexto_de_Encierro = 'X' and Ed_Comun_Primaria         = 'X'               
union all select  4 as idTN, CUE_Anexo as Codigo from DatosBase where Ed_Contexto_de_Encierro = 'X' and Ed_Comun_Secundaria             = 'X'         
union all select  5 as idTN, CUE_Anexo as Codigo from DatosBase where Ed_Contexto_de_Encierro = 'X' and Ed_Comun_Secundaria_Tecnica_INET      = 'X'   
union all select  6 as idTN, CUE_Anexo as Codigo from DatosBase where Ed_Contexto_de_Encierro = 'X' and Ed_Comun_Superior_no_Universitario      = 'X' 
union all select  7 as idTN, CUE_Anexo as Codigo from DatosBase where Ed_Contexto_de_Encierro = 'X' and Ed_Comun_Superior_No_Universitario_INET = 'X' 
union all select 46 as idTN, CUE_Anexo as Codigo from DatosBase where Ed_Contexto_de_Encierro = 'X' and Ed_Artistica_Secundaria                 = 'X' 
union all select 48 as idTN, CUE_Anexo as Codigo from DatosBase where Ed_Contexto_de_Encierro = 'X' and Ed_Artistica_Superior_no_Universitario  = 'X' 
union all select 50 as idTN, CUE_Anexo as Codigo from DatosBase where Ed_Contexto_de_Encierro = 'X' and Ed_Artistica_Cursos_y_Talleres          = 'X' 
union all select 23 as idTN, CUE_Anexo as Codigo from DatosBase where Ed_Contexto_de_Encierro = 'X' and Ed_Especial_Educacion_Temprana          = 'X' 
union all select 17 as idTN, CUE_Anexo as Codigo from DatosBase where Ed_Contexto_de_Encierro = 'X' and Ed_Especial_Inicial                     = 'X' 
union all select 18 as idTN, CUE_Anexo as Codigo from DatosBase where Ed_Contexto_de_Encierro = 'X' and Ed_Especial_Primaria                    = 'X' 
union all select 19 as idTN, CUE_Anexo as Codigo from DatosBase where Ed_Contexto_de_Encierro = 'X' and Ed_Especial_Secundaria                  = 'X' 
union all select 24 as idTN, CUE_Anexo as Codigo from DatosBase where Ed_Contexto_de_Encierro = 'X' and Ed_Especial_Integracion                 = 'X' 
union all select 31 as idTN, CUE_Anexo as Codigo from DatosBase where Ed_Contexto_de_Encierro = 'X' and Ed_Adultos_Primaria                     = 'X' 
union all select 39 as idTN, CUE_Anexo as Codigo from DatosBase where Ed_Contexto_de_Encierro = 'X' and Ed_Adultos_EGB3                         = 'X' 
union all select 32 as idTN, CUE_Anexo as Codigo from DatosBase where Ed_Contexto_de_Encierro = 'X' and Ed_Adultos_Secundaria                   = 'X' 
union all select 40 as idTN, CUE_Anexo as Codigo from DatosBase where Ed_Contexto_de_Encierro = 'X' and Ed_Adultos_Alfabetizacion               = 'X' 
union all select 41 as idTN, CUE_Anexo as Codigo from DatosBase where Ed_Contexto_de_Encierro = 'X' and Ed_Adultos_Formacion_Profesional        = 'X' 
union all select 42 as idTN, CUE_Anexo as Codigo from DatosBase where Ed_Contexto_de_Encierro = 'X' and Ed_Adultos_Formacion_Profesional_INET_  = 'X' 
union all select 58 as idTN, CUE_Anexo as Codigo from DatosBase where Ed_Contexto_de_Encierro = 'X' and Ed_Hospitalaria_Domiciliaria_Inicial    = 'X' 
union all select 59 as idTN, CUE_Anexo as Codigo from DatosBase where Ed_Contexto_de_Encierro = 'X' and Ed_Hospitalaria_Domiciliaria_Primaria   = 'X' 
union all select 60 as idTN, CUE_Anexo as Codigo from DatosBase where Ed_Contexto_de_Encierro = 'X' and Ed_Hospitalaria_Domiciliaria_Secundaria = 'X';