DELIMITER //

DROP PROCEDURE IF EXISTS GETAMBITO;

CREATE PROCEDURE GETAMBITO(PCIAID INT)
BEGIN
    IF PCIAID = -1 THEN
        SELECT ID, NOMBRE FROM Ambito ORDER BY NOMBRE;
    ELSE
        SELECT ID, NOMBRE FROM Ambito WHERE ID = PCIAID;
    END IF;
END //

DELIMITER ;