DELIMITER //

DROP PROCEDURE IF EXISTS GETPROVINCIA;

CREATE PROCEDURE GETPROVINCIA(PCIAID INT)
BEGIN
    IF PCIAID = -1 THEN
        SELECT ID, NOMBRE FROM Provincia ORDER BY NOMBRE;
    ELSE
        SELECT ID, NOMBRE FROM Provincia WHERE ID = PCIAID;
    END IF;
END //

DELIMITER ;