

DELIMITER //

DROP PROCEDURE IF EXISTS GETTABLES;

CREATE PROCEDURE GETTABLES()
BEGIN
    SELECT TABLE_NAME 
    FROM INFORMATION_SCHEMA.TABLES 
    WHERE TABLE_SCHEMA = DATABASE()
    AND TABLE_TYPE = 'BASE TABLE'
    ORDER BY TABLE_NAME;
END //

DELIMITER ;