DELIMITER //

DROP PROCEDURE IF EXISTS GETTIPOEDUCACION;

CREATE PROCEDURE GETTIPOEDUCACION(TEDID INT)
BEGIN
    IF TEDID = -1 THEN
        SELECT ID, NOMBRE FROM TipoEducacion ORDER BY NOMBRE;
    ELSE
        SELECT ID, NOMBRE FROM TipoEducacion WHERE ID = TEDID;
    END IF;
END //

DELIMITER ;