DELIMITER //

DROP PROCEDURE IF EXISTS GETTABLECOLUMNS;

CREATE PROCEDURE GETTABLECOLUMNS(IN PTAB VARCHAR(64))
BEGIN
    SELECT 
        ORDINAL_POSITION
        , COLUMN_NAME 
        , IS_NULLABLE
        , DATA_TYPE
        , CHARACTER_MAXIMUM_LENGTH
        , CHARACTER_OCTET_LENGTH
        , CHARACTER_SET_NAME
    FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE()
    AND UPPER(TABLE_NAME) = UPPER(PTAB)
    ORDER BY ORDINAL_POSITION;
END //

DELIMITER ;

