DELIMITER //

DROP PROCEDURE IF EXISTS GETVIEWS;

CREATE PROCEDURE GETVIEWS()
BEGIN
    SELECT TABLE_NAME AS VIEW_NAME
    FROM INFORMATION_SCHEMA.TABLES 
    WHERE TABLE_SCHEMA = DATABASE()
    AND TABLE_TYPE = 'VIEW'
    ORDER BY TABLE_NAME;
END //

DELIMITER ;